### ISSUE TITLE
Error en explicación de update_all de la clase ActiveRecord

### ISSUE THREAD

**Issue by marcelo-kazalukian** [KumbiaPHP/Documentation#34]
En la explicación de update_all de la clase ActiveRecord
https://github.com/KumbiaPHP/Documentation/blob/master/es/active-record.md#update_all

en el último ejemplo dice

(new Producto)->update_all( "precio = 0, estado='C'", "estado = 'B'");
Actualiza el atributo precio aumentándolo en un 20% y estado todos registros de la entidad producto donde el atributo estado es 'B'.

Debería decir 
Actualiza el atributo precio a 0 y el estado a 'C' para todos los registros de la entidad producto donde el atributo estado es 'B'.

**Comment by joanhey** [comment]
Gracias Marcelo
